CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE subjects (
    subjectid integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    description character varying(1000) NOT NULL,
    CONSTRAINT pk_subjects PRIMARY KEY (subjectid)
);

CREATE TABLE tiers (
    tierid integer GENERATED BY DEFAULT AS IDENTITY,
    rate integer NOT NULL,
    currentstreak integer NOT NULL,
    CONSTRAINT pk_tiers PRIMARY KEY (tierid)
);

CREATE TABLE users (
    userid integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(50) NOT NULL,
    phone character varying(50) NOT NULL,
    createdat timestamp with time zone NOT NULL,
    isdeleted boolean NOT NULL,
    isactive boolean NOT NULL,
    emailverificationtoken text,
    emailverificationtokenexpiry timestamp with time zone,
    refreshtoken text,
    refreshtokenexpirytime timestamp with time zone,
    CONSTRAINT pk_users PRIMARY KEY (userid)
);

CREATE TABLE conversations (
    conversationid integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    lastmessageat timestamp with time zone NOT NULL,
    isactive boolean NOT NULL,
    CONSTRAINT pk_conversations PRIMARY KEY (conversationid),
    CONSTRAINT fk_conversations_users_userid FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE RESTRICT
);

CREATE TABLE parents (
    parentid integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    address character varying(500) NOT NULL,
    CONSTRAINT pk_parents PRIMARY KEY (parentid),
    CONSTRAINT fk_parents_users_userid FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE RESTRICT
);

CREATE TABLE tutors (
    tutorid integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    bio character varying(1000) NOT NULL,
    revenue numeric(18,2) NOT NULL,
    rating double precision NOT NULL,
    isverified boolean NOT NULL,
    tierid integer,
    CONSTRAINT pk_tutors PRIMARY KEY (tutorid),
    CONSTRAINT fk_tutors_tiers_tierid FOREIGN KEY (tierid) REFERENCES tiers (tierid) ON DELETE SET NULL,
    CONSTRAINT fk_tutors_users_userid FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE RESTRICT
);

CREATE TABLE conversationusers (
    conversationid integer NOT NULL,
    userid integer NOT NULL,
    CONSTRAINT pk_conversationusers PRIMARY KEY (conversationid, userid),
    CONSTRAINT fk_conversationusers_conversations_conversationid FOREIGN KEY (conversationid) REFERENCES conversations (conversationid) ON DELETE CASCADE,
    CONSTRAINT fk_conversationusers_users_userid FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE RESTRICT
);

CREATE TABLE messages (
    messageid integer GENERATED BY DEFAULT AS IDENTITY,
    conversationid integer NOT NULL,
    userid integer NOT NULL,
    content character varying(2000) NOT NULL,
    isread boolean NOT NULL,
    createdat timestamp with time zone NOT NULL,
    isdeleted boolean NOT NULL,
    CONSTRAINT pk_messages PRIMARY KEY (messageid),
    CONSTRAINT fk_messages_conversations_conversationid FOREIGN KEY (conversationid) REFERENCES conversations (conversationid) ON DELETE CASCADE,
    CONSTRAINT fk_messages_users_userid FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE RESTRICT
);

CREATE TABLE students (
    studentid integer GENERATED BY DEFAULT AS IDENTITY,
    parentid integer,
    userid integer NOT NULL,
    grade numeric(5,2) NOT NULL,
    school character varying(255) NOT NULL,
    CONSTRAINT pk_students PRIMARY KEY (studentid),
    CONSTRAINT fk_students_parents_parentid FOREIGN KEY (parentid) REFERENCES parents (parentid) ON DELETE SET NULL,
    CONSTRAINT fk_students_users_userid FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE RESTRICT
);

CREATE TABLE availabilities (
    availabilityid integer GENERATED BY DEFAULT AS IDENTITY,
    tutorid integer NOT NULL,
    subjectid integer,
    dayofweek character varying(20) NOT NULL,
    mode character varying(20) NOT NULL,
    starttime timestamp with time zone NOT NULL,
    endtime timestamp with time zone NOT NULL,
    startcoursetime timestamp with time zone NOT NULL,
    endcoursetime timestamp with time zone NOT NULL,
    level character varying(50) NOT NULL,
    slot integer NOT NULL,
    priceperslot numeric(18,2) NOT NULL,
    status character varying(20) NOT NULL,
    CONSTRAINT pk_availabilities PRIMARY KEY (availabilityid),
    CONSTRAINT fk_availabilities_subjects_subjectid FOREIGN KEY (subjectid) REFERENCES subjects (subjectid) ON DELETE RESTRICT,
    CONSTRAINT fk_availabilities_tutors_tutorid FOREIGN KEY (tutorid) REFERENCES tutors (tutorid) ON DELETE CASCADE
);

CREATE TABLE favoritetutors (
    favoriteid integer GENERATED BY DEFAULT AS IDENTITY,
    tutorid integer NOT NULL,
    parentid integer NOT NULL,
    createdat timestamp with time zone NOT NULL,
    CONSTRAINT pk_favoritetutors PRIMARY KEY (favoriteid),
    CONSTRAINT fk_favoritetutors_parents_parentid FOREIGN KEY (parentid) REFERENCES parents (parentid) ON DELETE CASCADE,
    CONSTRAINT fk_favoritetutors_tutors_tutorid FOREIGN KEY (tutorid) REFERENCES tutors (tutorid) ON DELETE CASCADE
);

CREATE TABLE tutorbankaccounts (
    tutorbankaccountid integer GENERATED BY DEFAULT AS IDENTITY,
    tutorid integer NOT NULL,
    bankname character varying(255) NOT NULL,
    accountnumber character varying(100) NOT NULL,
    accountholdername character varying(255) NOT NULL,
    CONSTRAINT pk_tutorbankaccounts PRIMARY KEY (tutorbankaccountid),
    CONSTRAINT fk_tutorbankaccounts_tutors_tutorid FOREIGN KEY (tutorid) REFERENCES tutors (tutorid) ON DELETE CASCADE
);

CREATE TABLE tutorsubjects (
    subjectid integer NOT NULL,
    tutorid integer NOT NULL,
    CONSTRAINT pk_tutorsubjects PRIMARY KEY (subjectid, tutorid),
    CONSTRAINT fk_tutorsubjects_subjects_subjectid FOREIGN KEY (subjectid) REFERENCES subjects (subjectid) ON DELETE CASCADE,
    CONSTRAINT fk_tutorsubjects_tutors_tutorid FOREIGN KEY (tutorid) REFERENCES tutors (tutorid) ON DELETE CASCADE
);

CREATE TABLE wallets (
    walletid integer GENERATED BY DEFAULT AS IDENTITY,
    tutorid integer NOT NULL,
    balance numeric(18,2) NOT NULL,
    pendingbalance numeric(18,2) NOT NULL,
    CONSTRAINT pk_wallets PRIMARY KEY (walletid),
    CONSTRAINT fk_wallets_tutors_tutorid FOREIGN KEY (tutorid) REFERENCES tutors (tutorid) ON DELETE CASCADE
);

CREATE TABLE bookings (
    bookingid integer GENERATED BY DEFAULT AS IDENTITY,
    availabilityid integer NOT NULL,
    parentid integer NOT NULL,
    studentid integer NOT NULL,
    priceatbooking numeric(18,2) NOT NULL,
    createdat timestamp with time zone NOT NULL,
    status character varying(50) NOT NULL,
    isdeleted boolean NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (bookingid),
    CONSTRAINT fk_bookings_availabilities_availabilityid FOREIGN KEY (availabilityid) REFERENCES availabilities (availabilityid) ON DELETE RESTRICT,
    CONSTRAINT fk_bookings_parents_parentid FOREIGN KEY (parentid) REFERENCES parents (parentid) ON DELETE RESTRICT,
    CONSTRAINT fk_bookings_students_studentid FOREIGN KEY (studentid) REFERENCES students (studentid) ON DELETE RESTRICT
);

CREATE TABLE materials (
    materialid integer GENERATED BY DEFAULT AS IDENTITY,
    availabilityid integer NOT NULL,
    title character varying(255) NOT NULL,
    description character varying(2000) NOT NULL,
    fileurl character varying(500) NOT NULL,
    createdat timestamp with time zone NOT NULL,
    CONSTRAINT pk_materials PRIMARY KEY (materialid),
    CONSTRAINT fk_materials_availabilities_availabilityid FOREIGN KEY (availabilityid) REFERENCES availabilities (availabilityid) ON DELETE CASCADE
);

CREATE TABLE wallettransactions (
    wallettransactionid integer GENERATED BY DEFAULT AS IDENTITY,
    walletid integer NOT NULL,
    type character varying(50) NOT NULL,
    description character varying(500) NOT NULL,
    amount numeric(18,2) NOT NULL,
    createdat timestamp with time zone NOT NULL,
    CONSTRAINT pk_wallettransactions PRIMARY KEY (wallettransactionid),
    CONSTRAINT fk_wallettransactions_wallets_walletid FOREIGN KEY (walletid) REFERENCES wallets (walletid) ON DELETE CASCADE
);

CREATE TABLE homeworks (
    homeworkid integer GENERATED BY DEFAULT AS IDENTITY,
    bookingid integer NOT NULL,
    title character varying(255) NOT NULL,
    description character varying(2000) NOT NULL,
    url character varying(500) NOT NULL,
    duedate timestamp with time zone NOT NULL,
    uploadedat timestamp with time zone NOT NULL,
    CONSTRAINT pk_homeworks PRIMARY KEY (homeworkid),
    CONSTRAINT fk_homeworks_bookings_bookingid FOREIGN KEY (bookingid) REFERENCES bookings (bookingid) ON DELETE CASCADE
);

CREATE TABLE lessons (
    lessonid integer GENERATED BY DEFAULT AS IDENTITY,
    bookingid integer NOT NULL,
    scheduletime timestamp with time zone NOT NULL,
    duration integer NOT NULL,
    status character varying(50) NOT NULL,
    meetinglink character varying(500) NOT NULL,
    CONSTRAINT pk_lessons PRIMARY KEY (lessonid),
    CONSTRAINT fk_lessons_bookings_bookingid FOREIGN KEY (bookingid) REFERENCES bookings (bookingid) ON DELETE CASCADE
);

CREATE TABLE payments (
    paymentid integer GENERATED BY DEFAULT AS IDENTITY,
    bookingid integer NOT NULL,
    totalprice numeric(18,2) NOT NULL,
    status character varying(50) NOT NULL,
    createdat timestamp with time zone NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (paymentid),
    CONSTRAINT fk_payments_bookings_bookingid FOREIGN KEY (bookingid) REFERENCES bookings (bookingid) ON DELETE CASCADE
);

CREATE TABLE reviews (
    reviewid integer GENERATED BY DEFAULT AS IDENTITY,
    tutorid integer NOT NULL,
    bookingid integer NOT NULL,
    parentid integer,
    rating numeric(3,2) NOT NULL,
    comment character varying(2000) NOT NULL,
    uploadedat timestamp with time zone NOT NULL,
    CONSTRAINT pk_reviews PRIMARY KEY (reviewid),
    CONSTRAINT fk_reviews_bookings_bookingid FOREIGN KEY (bookingid) REFERENCES bookings (bookingid) ON DELETE RESTRICT,
    CONSTRAINT fk_reviews_parents_parentid FOREIGN KEY (parentid) REFERENCES parents (parentid) ON DELETE SET NULL,
    CONSTRAINT fk_reviews_tutors_tutorid FOREIGN KEY (tutorid) REFERENCES tutors (tutorid) ON DELETE RESTRICT
);

CREATE TABLE payouts (
    payoutid integer GENERATED BY DEFAULT AS IDENTITY,
    tutorid integer NOT NULL,
    wallettransactionid integer,
    amount character varying(50) NOT NULL,
    createdat_decimal numeric(18,2) NOT NULL,
    paidat timestamp with time zone,
    status character varying(50) NOT NULL,
    CONSTRAINT pk_payouts PRIMARY KEY (payoutid),
    CONSTRAINT fk_payouts_tutors_tutorid FOREIGN KEY (tutorid) REFERENCES tutors (tutorid) ON DELETE RESTRICT,
    CONSTRAINT fk_payouts_wallettransactions_wallettransactionid FOREIGN KEY (wallettransactionid) REFERENCES wallettransactions (wallettransactionid) ON DELETE SET NULL
);

CREATE TABLE essays (
    essayid integer GENERATED BY DEFAULT AS IDENTITY,
    homeworkid integer NOT NULL,
    questiontext character varying(1000) NOT NULL,
    points double precision NOT NULL,
    CONSTRAINT pk_essays PRIMARY KEY (essayid),
    CONSTRAINT fk_essays_homeworks_homeworkid FOREIGN KEY (homeworkid) REFERENCES homeworks (homeworkid) ON DELETE CASCADE
);

CREATE TABLE multiplechoicequestions (
    multiplechoicequestionid integer GENERATED BY DEFAULT AS IDENTITY,
    homeworkid integer NOT NULL,
    questiontext character varying(1000) NOT NULL,
    point double precision NOT NULL,
    CONSTRAINT pk_multiplechoicequestions PRIMARY KEY (multiplechoicequestionid),
    CONSTRAINT fk_multiplechoicequestions_homeworks_homeworkid FOREIGN KEY (homeworkid) REFERENCES homeworks (homeworkid) ON DELETE CASCADE
);

CREATE TABLE submissions (
    submissionid integer GENERATED BY DEFAULT AS IDENTITY,
    homeworkid integer NOT NULL,
    studentid integer NOT NULL,
    submittedat timestamp with time zone NOT NULL,
    totalscore double precision NOT NULL,
    CONSTRAINT pk_submissions PRIMARY KEY (submissionid),
    CONSTRAINT fk_submissions_homeworks_homeworkid FOREIGN KEY (homeworkid) REFERENCES homeworks (homeworkid) ON DELETE CASCADE,
    CONSTRAINT fk_submissions_students_studentid FOREIGN KEY (studentid) REFERENCES students (studentid) ON DELETE RESTRICT
);

CREATE TABLE attendances (
    attendanceid integer GENERATED BY DEFAULT AS IDENTITY,
    lessonid integer NOT NULL,
    studentid integer NOT NULL,
    status character varying(20) NOT NULL,
    attendedat timestamp with time zone,
    note character varying(500) NOT NULL,
    createdat timestamp with time zone NOT NULL,
    CONSTRAINT pk_attendances PRIMARY KEY (attendanceid),
    CONSTRAINT fk_attendances_lessons_lessonid FOREIGN KEY (lessonid) REFERENCES lessons (lessonid) ON DELETE CASCADE,
    CONSTRAINT fk_attendances_students_studentid FOREIGN KEY (studentid) REFERENCES students (studentid) ON DELETE RESTRICT
);

CREATE TABLE progressreports (
    reportid integer GENERATED BY DEFAULT AS IDENTITY,
    lessonid integer NOT NULL,
    tutorid integer NOT NULL,
    studentid integer NOT NULL,
    comments character varying(2000) NOT NULL,
    createdat interval NOT NULL,
    CONSTRAINT pk_progressreports PRIMARY KEY (reportid),
    CONSTRAINT fk_progressreports_lessons_lessonid FOREIGN KEY (lessonid) REFERENCES lessons (lessonid) ON DELETE RESTRICT,
    CONSTRAINT fk_progressreports_students_studentid FOREIGN KEY (studentid) REFERENCES students (studentid) ON DELETE RESTRICT,
    CONSTRAINT fk_progressreports_tutors_tutorid FOREIGN KEY (tutorid) REFERENCES tutors (tutorid) ON DELETE RESTRICT
);

CREATE TABLE questionoptionss (
    questionoptionid integer GENERATED BY DEFAULT AS IDENTITY,
    multiplechoicequestionid integer NOT NULL,
    iscorrect boolean NOT NULL,
    content character varying(500) NOT NULL,
    CONSTRAINT pk_questionoptionss PRIMARY KEY (questionoptionid),
    CONSTRAINT "fk_questionoptionss_multiplechoicequestions_multiplechoiceques~" FOREIGN KEY (multiplechoicequestionid) REFERENCES multiplechoicequestions (multiplechoicequestionid) ON DELETE CASCADE
);

CREATE TABLE essayanswers (
    essayanswerid integer GENERATED BY DEFAULT AS IDENTITY,
    submissionid integer NOT NULL,
    essayid integer NOT NULL,
    answertext character varying(5000) NOT NULL,
    score double precision NOT NULL,
    feedback character varying(2000) NOT NULL,
    CONSTRAINT pk_essayanswers PRIMARY KEY (essayanswerid),
    CONSTRAINT fk_essayanswers_essays_essayid FOREIGN KEY (essayid) REFERENCES essays (essayid) ON DELETE RESTRICT,
    CONSTRAINT fk_essayanswers_submissions_submissionid FOREIGN KEY (submissionid) REFERENCES submissions (submissionid) ON DELETE CASCADE
);

CREATE TABLE multiplechoicequestionanswers (
    multiplechoicequestionanswerid integer GENERATED BY DEFAULT AS IDENTITY,
    questionoptionid integer NOT NULL,
    submissionid integer NOT NULL,
    selectedoption character varying(500) NOT NULL,
    multiplechoicequestionid integer,
    CONSTRAINT pk_multiplechoicequestionanswers PRIMARY KEY (multiplechoicequestionanswerid),
    CONSTRAINT "fk_multiplechoicequestionanswers_multiplechoicequestions_multi~" FOREIGN KEY (multiplechoicequestionid) REFERENCES multiplechoicequestions (multiplechoicequestionid),
    CONSTRAINT "fk_multiplechoicequestionanswers_questionoptionss_questionopti~" FOREIGN KEY (questionoptionid) REFERENCES questionoptionss (questionoptionid) ON DELETE RESTRICT,
    CONSTRAINT fk_multiplechoicequestionanswers_submissions_submissionid FOREIGN KEY (submissionid) REFERENCES submissions (submissionid) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_attendances_lessonid_studentid ON attendances (lessonid, studentid);

CREATE INDEX ix_attendances_studentid ON attendances (studentid);

CREATE INDEX ix_availabilities_subjectid ON availabilities (subjectid);

CREATE INDEX ix_availabilities_tutorid_dayofweek ON availabilities (tutorid, dayofweek);

CREATE INDEX ix_bookings_availabilityid_studentid_status ON bookings (availabilityid, studentid, status);

CREATE INDEX ix_bookings_parentid ON bookings (parentid);

CREATE INDEX ix_bookings_studentid ON bookings (studentid);

CREATE INDEX ix_conversations_userid ON conversations (userid);

CREATE INDEX ix_conversationusers_userid ON conversationusers (userid);

CREATE INDEX ix_essayanswers_essayid ON essayanswers (essayid);

CREATE INDEX ix_essayanswers_submissionid ON essayanswers (submissionid);

CREATE INDEX ix_essays_homeworkid ON essays (homeworkid);

CREATE UNIQUE INDEX ix_favoritetutors_parentid_tutorid ON favoritetutors (parentid, tutorid);

CREATE INDEX ix_favoritetutors_tutorid ON favoritetutors (tutorid);

CREATE INDEX ix_homeworks_bookingid ON homeworks (bookingid);

CREATE INDEX ix_lessons_bookingid ON lessons (bookingid);

CREATE INDEX ix_materials_availabilityid ON materials (availabilityid);

CREATE INDEX ix_messages_conversationid ON messages (conversationid);

CREATE INDEX ix_messages_userid ON messages (userid);

CREATE INDEX ix_multiplechoicequestionanswers_multiplechoicequestionid ON multiplechoicequestionanswers (multiplechoicequestionid);

CREATE INDEX ix_multiplechoicequestionanswers_questionoptionid ON multiplechoicequestionanswers (questionoptionid);

CREATE INDEX ix_multiplechoicequestionanswers_submissionid ON multiplechoicequestionanswers (submissionid);

CREATE INDEX ix_multiplechoicequestions_homeworkid ON multiplechoicequestions (homeworkid);

CREATE UNIQUE INDEX ix_parents_userid ON parents (userid);

CREATE INDEX ix_payments_bookingid ON payments (bookingid);

CREATE INDEX ix_payouts_tutorid ON payouts (tutorid);

CREATE UNIQUE INDEX ix_payouts_wallettransactionid ON payouts (wallettransactionid);

CREATE INDEX ix_progressreports_lessonid ON progressreports (lessonid);

CREATE INDEX ix_progressreports_studentid ON progressreports (studentid);

CREATE INDEX ix_progressreports_tutorid ON progressreports (tutorid);

CREATE INDEX ix_questionoptionss_multiplechoicequestionid ON questionoptionss (multiplechoicequestionid);

CREATE INDEX ix_reviews_bookingid ON reviews (bookingid);

CREATE INDEX ix_reviews_parentid ON reviews (parentid);

CREATE INDEX ix_reviews_tutorid ON reviews (tutorid);

CREATE INDEX ix_students_parentid ON students (parentid);

CREATE UNIQUE INDEX ix_students_userid ON students (userid);

CREATE UNIQUE INDEX ix_submissions_homeworkid_studentid ON submissions (homeworkid, studentid);

CREATE INDEX ix_submissions_studentid ON submissions (studentid);

CREATE UNIQUE INDEX ix_tutorbankaccounts_tutorid ON tutorbankaccounts (tutorid);

CREATE INDEX ix_tutors_tierid ON tutors (tierid);

CREATE UNIQUE INDEX ix_tutors_userid ON tutors (userid);

CREATE INDEX ix_tutorsubjects_tutorid ON tutorsubjects (tutorid);

CREATE UNIQUE INDEX ix_users_email ON users (email);

CREATE UNIQUE INDEX ix_wallets_tutorid ON wallets (tutorid);

CREATE INDEX ix_wallettransactions_walletid ON wallettransactions (walletid);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260530174935_InitialCreate', '8.0.10');

COMMIT;

