// <auto-generated />
using System;
using DataAccessLayer.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(EduNestDbContext))]
    [Migration("20260608185155_AddUserAvatar")]
    partial class AddUserAvatar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Entities.AppMetric", b =>
                {
                    b.Property<int>("AppMetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("appmetricid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppMetricId"));

                    b.Property<string>("AppVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("appversion");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deviceid");

                    b.Property<string>("Platform")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("platform");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("AppMetricId")
                        .HasName("pk_appmetrics");

                    b.HasIndex("Type", "DeviceId")
                        .HasDatabaseName("ix_appmetrics_type_deviceid");

                    b.ToTable("appmetrics");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("attendanceid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime?>("AttendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attendedat");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer")
                        .HasColumnName("lessonid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.HasKey("AttendanceId")
                        .HasName("pk_attendances");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_attendances_studentid");

                    b.HasIndex("LessonId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_attendances_lessonid_studentid");

                    b.ToTable("attendances");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Availability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("availabilityid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AvailabilityId"));

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dayofweek");

                    b.Property<DateTime>("EndCourseTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("endcoursetime");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("endtime");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("level");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<decimal>("PricePerSlot")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("priceperslot");

                    b.Property<int>("Slot")
                        .HasColumnType("integer")
                        .HasColumnName("slot");

                    b.Property<DateTime>("StartCourseTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startcoursetime");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("starttime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subjectid");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer")
                        .HasColumnName("tutorid");

                    b.HasKey("AvailabilityId")
                        .HasName("pk_availabilities");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_availabilities_subjectid");

                    b.HasIndex("TutorId", "DayOfWeek")
                        .HasDatabaseName("ix_availabilities_tutorid_dayofweek");

                    b.ToTable("availabilities");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookingId"));

                    b.Property<int>("AvailabilityId")
                        .HasColumnType("integer")
                        .HasColumnName("availabilityid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parentid");

                    b.Property<decimal>("PriceAtBooking")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("priceatbooking");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int?>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("BookingId")
                        .HasName("pk_bookings");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_bookings_parentid");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_bookings_studentid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_bookings_userid");

                    b.HasIndex("AvailabilityId", "StudentId", "Status")
                        .HasDatabaseName("ix_bookings_availabilityid_studentid_status");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Conversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("conversationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConversationId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmessageat");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("ConversationId")
                        .HasName("pk_conversations");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_conversations_userid");

                    b.ToTable("conversations");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ConversationUser", b =>
                {
                    b.Property<int>("ConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("conversationid");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("ConversationId", "UserId")
                        .HasName("pk_conversationusers");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_conversationusers_userid");

                    b.ToTable("conversationusers");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Essay", b =>
                {
                    b.Property<int>("EssayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("essayid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EssayId"));

                    b.Property<int>("HomeworkId")
                        .HasColumnType("integer")
                        .HasColumnName("homeworkid");

                    b.Property<double>("Points")
                        .HasColumnType("double precision")
                        .HasColumnName("points");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("questiontext");

                    b.HasKey("EssayId")
                        .HasName("pk_essays");

                    b.HasIndex("HomeworkId")
                        .HasDatabaseName("ix_essays_homeworkid");

                    b.ToTable("essays");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.EssayAnswer", b =>
                {
                    b.Property<int>("EssayAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("essayanswerid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EssayAnswerId"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("answertext");

                    b.Property<int>("EssayId")
                        .HasColumnType("integer")
                        .HasColumnName("essayid");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("feedback");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("integer")
                        .HasColumnName("submissionid");

                    b.HasKey("EssayAnswerId")
                        .HasName("pk_essayanswers");

                    b.HasIndex("EssayId")
                        .HasDatabaseName("ix_essayanswers_essayid");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ix_essayanswers_submissionid");

                    b.ToTable("essayanswers");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.FavoriteTutor", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("favoriteid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FavoriteId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parentid");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer")
                        .HasColumnName("tutorid");

                    b.HasKey("FavoriteId")
                        .HasName("pk_favoritetutors");

                    b.HasIndex("TutorId")
                        .HasDatabaseName("ix_favoritetutors_tutorid");

                    b.HasIndex("ParentId", "TutorId")
                        .IsUnique()
                        .HasDatabaseName("ix_favoritetutors_parentid_tutorid");

                    b.ToTable("favoritetutors");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Homework", b =>
                {
                    b.Property<int>("HomeworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("homeworkid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HomeworkId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("duedate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploadedat");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("HomeworkId")
                        .HasName("pk_homeworks");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_homeworks_bookingid");

                    b.ToTable("homeworks");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lessonid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LessonId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<string>("MeetingLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("meetinglink");

                    b.Property<DateTime>("ScheduleTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduletime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("LessonId")
                        .HasName("pk_lessons");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_lessons_bookingid");

                    b.ToTable("lessons");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("materialid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaterialId"));

                    b.Property<int>("AvailabilityId")
                        .HasColumnType("integer")
                        .HasColumnName("availabilityid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fileurl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("MaterialId")
                        .HasName("pk_materials");

                    b.HasIndex("AvailabilityId")
                        .HasDatabaseName("ix_materials_availabilityid");

                    b.ToTable("materials");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("messageid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("conversationid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("isread");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("MessageId")
                        .HasName("pk_messages");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_messages_conversationid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_messages_userid");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.MultipleChoiceQuestion", b =>
                {
                    b.Property<int>("MultipleChoiceQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("multiplechoicequestionid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MultipleChoiceQuestionId"));

                    b.Property<int>("HomeworkId")
                        .HasColumnType("integer")
                        .HasColumnName("homeworkid");

                    b.Property<double>("Point")
                        .HasColumnType("double precision")
                        .HasColumnName("point");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("questiontext");

                    b.HasKey("MultipleChoiceQuestionId")
                        .HasName("pk_multiplechoicequestions");

                    b.HasIndex("HomeworkId")
                        .HasDatabaseName("ix_multiplechoicequestions_homeworkid");

                    b.ToTable("multiplechoicequestions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.MultipleChoiceQuestionAnswer", b =>
                {
                    b.Property<int>("MultipleChoiceQuestionAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("multiplechoicequestionanswerid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MultipleChoiceQuestionAnswerId"));

                    b.Property<int?>("MultipleChoiceQuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("multiplechoicequestionid");

                    b.Property<int>("QuestionOptionId")
                        .HasColumnType("integer")
                        .HasColumnName("questionoptionid");

                    b.Property<string>("SelectedOption")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("selectedoption");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("integer")
                        .HasColumnName("submissionid");

                    b.HasKey("MultipleChoiceQuestionAnswerId")
                        .HasName("pk_multiplechoicequestionanswers");

                    b.HasIndex("MultipleChoiceQuestionId")
                        .HasDatabaseName("ix_multiplechoicequestionanswers_multiplechoicequestionid");

                    b.HasIndex("QuestionOptionId")
                        .HasDatabaseName("ix_multiplechoicequestionanswers_questionoptionid");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ix_multiplechoicequestionanswers_submissionid");

                    b.ToTable("multiplechoicequestionanswers");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Parent", b =>
                {
                    b.Property<int>("ParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("parentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParentId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("ParentId")
                        .HasName("pk_parents");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_parents_userid");

                    b.ToTable("parents");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("paymentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("checkouturl");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paidat");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<long>("ProviderOrderCode")
                        .HasColumnType("bigint")
                        .HasColumnName("providerordercode");

                    b.Property<string>("QrCode")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("qrcode");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("totalprice");

                    b.HasKey("PaymentId")
                        .HasName("pk_payments");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_payments_bookingid");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Payout", b =>
                {
                    b.Property<int>("PayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payoutid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PayoutId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paidat");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requestedat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer")
                        .HasColumnName("tutorid");

                    b.Property<int?>("WalletTransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("wallettransactionid");

                    b.HasKey("PayoutId")
                        .HasName("pk_payouts");

                    b.HasIndex("TutorId")
                        .HasDatabaseName("ix_payouts_tutorid");

                    b.HasIndex("WalletTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_payouts_wallettransactionid");

                    b.ToTable("payouts");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ProgressReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("reportid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comments");

                    b.Property<TimeSpan>("CreatedAt")
                        .HasColumnType("interval")
                        .HasColumnName("createdat");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer")
                        .HasColumnName("lessonid");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer")
                        .HasColumnName("tutorid");

                    b.HasKey("ReportId")
                        .HasName("pk_progressreports");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_progressreports_lessonid");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_progressreports_studentid");

                    b.HasIndex("TutorId")
                        .HasDatabaseName("ix_progressreports_tutorid");

                    b.ToTable("progressreports");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.QuestionOption", b =>
                {
                    b.Property<int>("QuestionOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("questionoptionid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionOptionId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("content");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("iscorrect");

                    b.Property<int>("MultipleChoiceQuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("multiplechoicequestionid");

                    b.HasKey("QuestionOptionId")
                        .HasName("pk_questionoptionss");

                    b.HasIndex("MultipleChoiceQuestionId")
                        .HasDatabaseName("ix_questionoptionss_multiplechoicequestionid");

                    b.ToTable("questionoptionss");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("reviewid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parentid");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("rating");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer")
                        .HasColumnName("tutorid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploadedat");

                    b.HasKey("ReviewId")
                        .HasName("pk_reviews");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_reviews_bookingid");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_reviews_parentid");

                    b.HasIndex("TutorId")
                        .HasDatabaseName("ix_reviews_tutorid");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("grade");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parentid");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("school");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("StudentId")
                        .HasName("pk_students");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_students_parentid");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_students_userid");

                    b.ToTable("students");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("subjectid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("SubjectId")
                        .HasName("pk_subjects");

                    b.ToTable("subjects");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Submission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("submissionid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubmissionId"));

                    b.Property<int>("HomeworkId")
                        .HasColumnType("integer")
                        .HasColumnName("homeworkid");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submittedat");

                    b.Property<double>("TotalScore")
                        .HasColumnType("double precision")
                        .HasColumnName("totalscore");

                    b.HasKey("SubmissionId")
                        .HasName("pk_submissions");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_submissions_studentid");

                    b.HasIndex("HomeworkId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_submissions_homeworkid_studentid");

                    b.ToTable("submissions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.SupportReport", b =>
                {
                    b.Property<int>("SupportReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("supportreportid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupportReportId"));

                    b.Property<string>("AdminNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("adminnote");

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int?>("LessonId")
                        .HasColumnType("integer")
                        .HasColumnName("lessonid");

                    b.Property<int?>("PayoutId")
                        .HasColumnType("integer")
                        .HasColumnName("payoutid");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewedat");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("SupportReportId")
                        .HasName("pk_supportreports");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_supportreports_createdat");

                    b.HasIndex("Role", "Status")
                        .HasDatabaseName("ix_supportreports_role_status");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_supportreports_userid_status");

                    b.ToTable("supportreports");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.SupportReportProofImage", b =>
                {
                    b.Property<int>("SupportReportProofImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("supportreportproofimageid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupportReportProofImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("publicid");

                    b.Property<int>("SupportReportId")
                        .HasColumnType("integer")
                        .HasColumnName("supportreportid");

                    b.HasKey("SupportReportProofImageId")
                        .HasName("pk_supportreportproofimages");

                    b.HasIndex("SupportReportId")
                        .HasDatabaseName("ix_supportreportproofimages_supportreportid");

                    b.ToTable("supportreportproofimages");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Tier", b =>
                {
                    b.Property<int>("TierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tierid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TierId"));

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer")
                        .HasColumnName("currentstreak");

                    b.Property<int>("Rate")
                        .HasColumnType("integer")
                        .HasColumnName("rate");

                    b.HasKey("TierId")
                        .HasName("pk_tiers");

                    b.ToTable("tiers");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Tutor", b =>
                {
                    b.Property<int>("TutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tutorid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TutorId"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("bio");

                    b.Property<string>("CccdBackPublicId")
                        .HasColumnType("text")
                        .HasColumnName("cccdbackpublicid");

                    b.Property<string>("CccdFrontPublicId")
                        .HasColumnType("text")
                        .HasColumnName("cccdfrontpublicid");

                    b.Property<string>("CertificatePublicId")
                        .HasColumnType("text")
                        .HasColumnName("certificatepublicid");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("isverified");

                    b.Property<string>("NationalIdNumber")
                        .HasColumnType("text")
                        .HasColumnName("nationalidnumber");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("revenue");

                    b.Property<int?>("TierId")
                        .HasColumnType("integer")
                        .HasColumnName("tierid");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<string>("VerificationRejectReason")
                        .HasColumnType("text")
                        .HasColumnName("verificationrejectreason");

                    b.Property<DateTime?>("VerificationReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verificationreviewedat");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verificationstatus");

                    b.Property<DateTime?>("VerificationSubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verificationsubmittedat");

                    b.HasKey("TutorId")
                        .HasName("pk_tutors");

                    b.HasIndex("TierId")
                        .HasDatabaseName("ix_tutors_tierid");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_tutors_userid");

                    b.ToTable("tutors");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.TutorBankAccount", b =>
                {
                    b.Property<int>("TutorBankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tutorbankaccountid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TutorBankAccountId"));

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("accountholdername");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("accountnumber");

                    b.Property<string>("BankBin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bankbin");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bankname");

                    b.Property<string>("BranchName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("branchname");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer")
                        .HasColumnName("tutorid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("TutorBankAccountId")
                        .HasName("pk_tutorbankaccounts");

                    b.HasIndex("TutorId")
                        .IsUnique()
                        .HasDatabaseName("ix_tutorbankaccounts_tutorid");

                    b.ToTable("tutorbankaccounts");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.TutorReport", b =>
                {
                    b.Property<int>("TutorReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tutorreportid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TutorReportId"));

                    b.Property<string>("AdminNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("adminnote");

                    b.Property<int>("AvailabilityId")
                        .HasColumnType("integer")
                        .HasColumnName("availabilityid");

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int?>("LessonId")
                        .HasColumnType("integer")
                        .HasColumnName("lessonid");

                    b.Property<int>("ReporterUserId")
                        .HasColumnType("integer")
                        .HasColumnName("reporteruserid");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewedat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer")
                        .HasColumnName("tutorid");

                    b.HasKey("TutorReportId")
                        .HasName("pk_tutorreports");

                    b.HasIndex("AvailabilityId")
                        .HasDatabaseName("ix_tutorreports_availabilityid");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_tutorreports_bookingid");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tutorreports_createdat");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_tutorreports_lessonid");

                    b.HasIndex("ReporterUserId", "BookingId")
                        .HasDatabaseName("ix_tutorreports_reporteruserid_bookingid");

                    b.HasIndex("TutorId", "Status")
                        .HasDatabaseName("ix_tutorreports_tutorid_status");

                    b.ToTable("tutorreports");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.TutorReportProofImage", b =>
                {
                    b.Property<int>("TutorReportProofImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tutorreportproofimageid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TutorReportProofImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("publicid");

                    b.Property<int>("TutorReportId")
                        .HasColumnType("integer")
                        .HasColumnName("tutorreportid");

                    b.HasKey("TutorReportProofImageId")
                        .HasName("pk_tutorreportproofimages");

                    b.HasIndex("TutorReportId")
                        .HasDatabaseName("ix_tutorreportproofimages_tutorreportid");

                    b.ToTable("tutorreportproofimages");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.TutorSubject", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subjectid");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer")
                        .HasColumnName("tutorid");

                    b.HasKey("SubjectId", "TutorId")
                        .HasName("pk_tutorsubjects");

                    b.HasIndex("TutorId")
                        .HasDatabaseName("ix_tutorsubjects_tutorid");

                    b.ToTable("tutorsubjects");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarPublicId")
                        .HasColumnType("text")
                        .HasColumnName("avatarpublicid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text")
                        .HasColumnName("emailverificationtoken");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emailverificationtokenexpiry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refreshtoken");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refreshtokenexpirytime");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("walletid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WalletId"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance");

                    b.Property<decimal>("PendingBalance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("pendingbalance");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer")
                        .HasColumnName("tutorid");

                    b.HasKey("WalletId")
                        .HasName("pk_wallets");

                    b.HasIndex("TutorId")
                        .IsUnique()
                        .HasDatabaseName("ix_wallets_tutorid");

                    b.ToTable("wallets");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.WalletTransaction", b =>
                {
                    b.Property<int>("WalletTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("wallettransactionid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WalletTransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer")
                        .HasColumnName("walletid");

                    b.HasKey("WalletTransactionId")
                        .HasName("pk_wallettransactions");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("ix_wallettransactions_walletid");

                    b.ToTable("wallettransactions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Attendance", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Lesson", "Lesson")
                        .WithMany("Attendances")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendances_lessons_lessonid");

                    b.HasOne("DataAccessLayer.Entities.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendances_students_studentid");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Availability", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Subject", "Subject")
                        .WithMany("Availabilities")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_availabilities_subjects_subjectid");

                    b.HasOne("DataAccessLayer.Entities.Tutor", "Tutor")
                        .WithMany("Availabilities")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_availabilities_tutors_tutorid");

                    b.Navigation("Subject");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Booking", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Availability", "Availability")
                        .WithMany("Bookings")
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_availabilities_availabilityid");

                    b.HasOne("DataAccessLayer.Entities.Parent", "Parent")
                        .WithMany("Bookings")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_bookings_parents_parentid");

                    b.HasOne("DataAccessLayer.Entities.Student", "Student")
                        .WithMany("Bookings")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_bookings_students_studentid");

                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_bookings_users_userid");

                    b.Navigation("Availability");

                    b.Navigation("Parent");

                    b.Navigation("Student");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Conversation", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_users_userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ConversationUser", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Conversation", "Conversation")
                        .WithMany("ConversationUsers")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversationusers_conversations_conversationid");

                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithMany("ConversationUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversationusers_users_userid");

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Essay", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Homework", "Homework")
                        .WithMany("Essays")
                        .HasForeignKey("HomeworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_essays_homeworks_homeworkid");

                    b.Navigation("Homework");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.EssayAnswer", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Essay", "Essay")
                        .WithMany("EssayAnswers")
                        .HasForeignKey("EssayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_essayanswers_essays_essayid");

                    b.HasOne("DataAccessLayer.Entities.Submission", "Submission")
                        .WithMany("EssayAnswers")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_essayanswers_submissions_submissionid");

                    b.Navigation("Essay");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.FavoriteTutor", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Parent", "Parent")
                        .WithMany("FavoriteTutors")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favoritetutors_parents_parentid");

                    b.HasOne("DataAccessLayer.Entities.Tutor", "Tutor")
                        .WithMany("FavoriteTutors")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favoritetutors_tutors_tutorid");

                    b.Navigation("Parent");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Homework", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Booking", "Booking")
                        .WithMany("Homeworks")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_homeworks_bookings_bookingid");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Lesson", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Booking", "Booking")
                        .WithMany("Lessons")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_bookings_bookingid");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Material", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Availability", "Availability")
                        .WithMany("Materials")
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_materials_availabilities_availabilityid");

                    b.Navigation("Availability");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Message", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversations_conversationid");

                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_userid");

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.MultipleChoiceQuestion", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Homework", "Homework")
                        .WithMany("MultipleChoiceQuestions")
                        .HasForeignKey("HomeworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_multiplechoicequestions_homeworks_homeworkid");

                    b.Navigation("Homework");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.MultipleChoiceQuestionAnswer", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.MultipleChoiceQuestion", null)
                        .WithMany("Answers")
                        .HasForeignKey("MultipleChoiceQuestionId")
                        .HasConstraintName("fk_multiplechoicequestionanswers_multiplechoicequestions_multi~");

                    b.HasOne("DataAccessLayer.Entities.QuestionOption", "QuestionOption")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_multiplechoicequestionanswers_questionoptionss_questionopti~");

                    b.HasOne("DataAccessLayer.Entities.Submission", "Submission")
                        .WithMany("MultipleChoiceQuestionAnswers")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_multiplechoicequestionanswers_submissions_submissionid");

                    b.Navigation("QuestionOption");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Parent", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithOne("Parent")
                        .HasForeignKey("DataAccessLayer.Entities.Parent", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parents_users_userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Payment", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_bookings_bookingid");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Payout", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Tutor", "Tutor")
                        .WithMany("Payouts")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payouts_tutors_tutorid");

                    b.HasOne("DataAccessLayer.Entities.WalletTransaction", "WalletTransaction")
                        .WithOne("Payout")
                        .HasForeignKey("DataAccessLayer.Entities.Payout", "WalletTransactionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_payouts_wallettransactions_wallettransactionid");

                    b.Navigation("Tutor");

                    b.Navigation("WalletTransaction");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ProgressReport", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Lesson", "Lesson")
                        .WithMany("ProgressReports")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_progressreports_lessons_lessonid");

                    b.HasOne("DataAccessLayer.Entities.Student", "Student")
                        .WithMany("ProgressReports")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_progressreports_students_studentid");

                    b.HasOne("DataAccessLayer.Entities.Tutor", "Tutor")
                        .WithMany("ProgressReports")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_progressreports_tutors_tutorid");

                    b.Navigation("Lesson");

                    b.Navigation("Student");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.QuestionOption", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.MultipleChoiceQuestion", "MultipleChoiceQuestion")
                        .WithMany("QuestionOptions")
                        .HasForeignKey("MultipleChoiceQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questionoptionss_multiplechoicequestions_multiplechoiceques~");

                    b.Navigation("MultipleChoiceQuestion");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Review", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Booking", "Booking")
                        .WithMany("Reviews")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_bookings_bookingid");

                    b.HasOne("DataAccessLayer.Entities.Parent", "Parent")
                        .WithMany("Reviews")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_reviews_parents_parentid");

                    b.HasOne("DataAccessLayer.Entities.Tutor", "Tutor")
                        .WithMany("Reviews")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_tutors_tutorid");

                    b.Navigation("Booking");

                    b.Navigation("Parent");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Student", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Parent", "Parent")
                        .WithMany("Students")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_students_parents_parentid");

                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("DataAccessLayer.Entities.Student", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_students_users_userid");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Submission", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Homework", "Homework")
                        .WithMany("Submissions")
                        .HasForeignKey("HomeworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_homeworks_homeworkid");

                    b.HasOne("DataAccessLayer.Entities.Student", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_students_studentid");

                    b.Navigation("Homework");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.SupportReport", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_supportreports_users_userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.SupportReportProofImage", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.SupportReport", "SupportReport")
                        .WithMany("ProofImages")
                        .HasForeignKey("SupportReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supportreportproofimages_supportreports_supportreportid");

                    b.Navigation("SupportReport");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Tutor", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Tier", "Tier")
                        .WithMany("Tutors")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tutors_tiers_tierid");

                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithOne("Tutor")
                        .HasForeignKey("DataAccessLayer.Entities.Tutor", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tutors_users_userid");

                    b.Navigation("Tier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.TutorBankAccount", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Tutor", "Tutor")
                        .WithOne("BankAccount")
                        .HasForeignKey("DataAccessLayer.Entities.TutorBankAccount", "TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tutorbankaccounts_tutors_tutorid");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.TutorReport", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Availability", "Availability")
                        .WithMany()
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tutorreports_availabilities_availabilityid");

                    b.HasOne("DataAccessLayer.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tutorreports_bookings_bookingid");

                    b.HasOne("DataAccessLayer.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tutorreports_lessons_lessonid");

                    b.HasOne("DataAccessLayer.Entities.User", "ReporterUser")
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tutorreports_users_reporteruserid");

                    b.HasOne("DataAccessLayer.Entities.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tutorreports_tutors_tutorid");

                    b.Navigation("Availability");

                    b.Navigation("Booking");

                    b.Navigation("Lesson");

                    b.Navigation("ReporterUser");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.TutorReportProofImage", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.TutorReport", "TutorReport")
                        .WithMany("ProofImages")
                        .HasForeignKey("TutorReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tutorreportproofimages_tutorreports_tutorreportid");

                    b.Navigation("TutorReport");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.TutorSubject", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Subject", "Subject")
                        .WithMany("TutorSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tutorsubjects_subjects_subjectid");

                    b.HasOne("DataAccessLayer.Entities.Tutor", "Tutor")
                        .WithMany("TutorSubjects")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tutorsubjects_tutors_tutorid");

                    b.Navigation("Subject");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Wallet", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Tutor", "Tutor")
                        .WithOne("Wallet")
                        .HasForeignKey("DataAccessLayer.Entities.Wallet", "TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wallets_tutors_tutorid");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.WalletTransaction", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Wallet", "Wallet")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wallettransactions_wallets_walletid");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Availability", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Booking", b =>
                {
                    b.Navigation("Homeworks");

                    b.Navigation("Lessons");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Conversation", b =>
                {
                    b.Navigation("ConversationUsers");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Essay", b =>
                {
                    b.Navigation("EssayAnswers");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Homework", b =>
                {
                    b.Navigation("Essays");

                    b.Navigation("MultipleChoiceQuestions");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Lesson", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("ProgressReports");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.MultipleChoiceQuestion", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("QuestionOptions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Parent", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("FavoriteTutors");

                    b.Navigation("Reviews");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.QuestionOption", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Bookings");

                    b.Navigation("ProgressReports");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Subject", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("TutorSubjects");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Submission", b =>
                {
                    b.Navigation("EssayAnswers");

                    b.Navigation("MultipleChoiceQuestionAnswers");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.SupportReport", b =>
                {
                    b.Navigation("ProofImages");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Tier", b =>
                {
                    b.Navigation("Tutors");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Tutor", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("BankAccount")
                        .IsRequired();

                    b.Navigation("FavoriteTutors");

                    b.Navigation("Payouts");

                    b.Navigation("ProgressReports");

                    b.Navigation("Reviews");

                    b.Navigation("TutorSubjects");

                    b.Navigation("Wallet")
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Entities.TutorReport", b =>
                {
                    b.Navigation("ProofImages");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.User", b =>
                {
                    b.Navigation("ConversationUsers");

                    b.Navigation("Messages");

                    b.Navigation("Parent")
                        .IsRequired();

                    b.Navigation("Student")
                        .IsRequired();

                    b.Navigation("Tutor")
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Wallet", b =>
                {
                    b.Navigation("WalletTransactions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.WalletTransaction", b =>
                {
                    b.Navigation("Payout")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
